version: '2'
services:
  # MongoDB: https://hub.docker.com/_/mongo/#
  mongodb:
    container_name: graylogpv_mongodb
    image: mongo:3
    volumes:
      - graylogpv_mongo_data:/data/db
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html#
  elasticsearch:
    container_name: graylogpv_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    volumes:
      - graylogpv_es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    container_name: graylogpv_graylog
    image: graylog/graylog:3.3
    volumes:
      - graylogpv_graylog_data:/usr/share/graylog/data
    environment:
      # CHANGE ME (must be at least 16 characters)!
      #- GRAYLOG_PASSWORD_SECRET=somepasswordpepper
#      - GRAYLOG_PASSWORD_SECRET=testetestetesteteste
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=f91a799a01ebac97c8995f50381b5be0d43ca7eb0c6a6c6bc07603c5a922d1fa
      - GRAYLOG_HTTP_EXTERNAL_URI=http://172.17.1.245:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  graylogpv_mongo_data:
    external: true
  graylogpv_es_data:
    external: true
  graylogpv_graylog_data:
    external: true
